const fs = require('fs');
const path = require('path');

function mk(id, t, g, d, qs) {
    const qStr = qs.map((q, i) => {
        return '    { id: "' + id + '-' + (i + 1) + '", type: "multiple-choice", question: "' + q.q.replace(/"/g, '\\"').replace(/\\'/g, "\\\\'") + '", options: ' + JSON.stringify(q.o) + ', correctAnswer: "' + q.c.replace(/"/g, '\\"').replace(/\\'/g, "\\\\'") + '" }';
    }).join(',\n');
    const dEsc = d.replace(/"/g, '\\"').replace(/'/g, "\\\\'");
    const gEsc = g.replace(/'/g, "\\\\'");
    const tEsc = t.replace(/'/g, "\\\\'");

    return `import { Lesson } from '../../types';
export const lesson${id}: Lesson = { id: ${id}, title: "Lesson ${id}: ${tEsc}", grammar: "${gEsc}", theory: { sections: [
    { title: "📖 Description", content: "${dEsc}" },
    { title: "📝 Key Rules", content: "Review the examples and practice the tasks below to master this topic." },
    { title: "🗣️ Examples", content: "Examples and key terms are integrated into the exercises below." },
    { title: "📚 Vocabulary", content: "Essential vocabulary for this lesson is covered in the tasks." }
] }, tasks: [
${qStr}
] };`;
}

const lessons = [
    {
        id: 66, t: "Practical I\\'rab — Nouns", g: "I\\'rab al-Ism", d: "Practice identifying Marfu', Mansub, and Majrur states of nouns in real sentences.",
        qs: [{ q: "The sign of Marfu' for regular nouns is:", o: ["Fatha", "Kasra", "Damma", "Sukun"], c: "Damma" }, { q: "The sign of Mansub for regular nouns is:", o: ["Damma", "Kasra", "Fatha", "Sukun"], c: "Fatha" }, { q: "The sign of Majrur for regular nouns is:", o: ["Damma", "Fatha", "Kasra", "Sukun"], c: "Kasra" }, { q: "After a preposition, the noun is:", o: ["Marfu'", "Mansub", "Majrur", "Majzum"], c: "Majrur" }, { q: "Translate: اسم مرفوع", o: ["Mansub noun", "Marfu' noun", "Majrur noun", "Indeclinable"], c: "Marfu' noun" }, { q: "Translate: اسم منصوب", o: ["Marfu' noun", "Mansub noun", "Majrur noun", "Indeclinable"], c: "Mansub noun" }, { q: "Translate: اسم مجرور", o: ["Marfu' noun", "Mansub noun", "Majrur noun", "Indeclinable"], c: "Majrur noun" }, { q: "What does إعراب mean?", o: ["Translation", "Grammatical parsing", "Writing", "Reading"], c: "Grammatical parsing" }, { q: "What does علامة mean?", o: ["Word", "Sign/Marker", "Sentence", "Letter"], c: "Sign/Marker" }, { q: "Diptotes take fatha instead of:", o: ["Damma", "Kasra (in Majrur)", "Sukun", "Fatha"], c: "Kasra (in Majrur)" }]
    },
    {
        id: 67, t: "Practical I\\'rab — Verbs", g: "I\\'rab al-Fi\\'l", d: "Practice parsing verbs: past tense (mabni), present tense (mu'rab), and imperative (mabni).",
        qs: [{ q: "Past tense verbs are:", o: ["Declinable", "Indeclinable (Mabni)", "Always Marfu'", "Always Mansub"], c: "Indeclinable (Mabni)" }, { q: "Present tense verbs are by default:", o: ["Mabni", "Marfu'", "Mansub", "Majzum"], c: "Marfu'" }, { q: "After لَمْ, the present verb is:", o: ["Marfu'", "Mansub", "Majzum", "Mabni"], c: "Majzum" }, { q: "After أَنْ, the present verb is:", o: ["Marfu'", "Mansub", "Majzum", "Mabni"], c: "Mansub" }, { q: "Translate: فعل ماضٍ", o: ["Present verb", "Past tense verb", "Imperative", "Verbal noun"], c: "Past tense verb" }, { q: "Translate: فعل مضارع", o: ["Past verb", "Present tense verb", "Imperative", "Participle"], c: "Present tense verb" }, { q: "Translate: فعل أمر", o: ["Past verb", "Present verb", "Imperative verb", "Passive verb"], c: "Imperative verb" }, { q: "What does مبني mean?", o: ["Declinable", "Indeclinable/Fixed", "Variable", "Free"], c: "Indeclinable/Fixed" }, { q: "What does معرب mean?", o: ["Indeclinable", "Declinable", "Past only", "Imperative only"], c: "Declinable" }, { q: "The Majzum sign on regular verbs is:", o: ["Damma", "Fatha", "Kasra", "Sukun"], c: "Sukun" }]
    },
    {
        id: 68, t: "Types of Khabar", g: "Anwa\\' al-Khabar", d: "The Khabar can be: 1) Mufrad (single word), 2) Jumla (sentence), 3) Shibh Jumla (semi-sentence).",
        qs: [{ q: "How many types of Khabar exist?", o: ["Two", "Three", "Four", "Five"], c: "Three" }, { q: "العلم نور has which Khabar type?", o: ["Jumla", "Mufrad", "Shibh Jumla", "None"], c: "Mufrad" }, { q: "الكتاب في الحقيبة has which type?", o: ["Mufrad", "Jumla fi'liyya", "Shibh Jumla", "Jumla ismiyya"], c: "Shibh Jumla" }, { q: "محمد يدرس has which type?", o: ["Mufrad", "Jumla fi'liyya", "Shibh Jumla", "None"], c: "Jumla fi'liyya" }, { q: "Translate: خبر مفرد", o: ["Sentence predicate", "Single-word predicate", "Semi-sentence", "Clause"], c: "Single-word predicate" }, { q: "Translate: خبر جملة", o: ["Single predicate", "Sentence predicate", "Semi-sentence", "Fragment"], c: "Sentence predicate" }, { q: "Translate: شبه جملة", o: ["Full sentence", "Semi-sentence", "Fragment", "Clause"], c: "Semi-sentence" }, { q: "What does مفرد mean here?", o: ["Plural", "Single/Individual", "Dual", "Collective"], c: "Single/Individual" }, { q: "A prepositional phrase as Khabar is:", o: ["Mufrad", "Jumla", "Shibh Jumla", "Sifa"], c: "Shibh Jumla" }, { q: "What does أنواع mean?", o: ["Rules", "Types/Kinds", "Books", "Lessons"], c: "Types/Kinds" }]
    },
    {
        id: 69, t: "Advanced Idafa", g: "Al-Idafa al-Mutaqaddima", d: "Advanced Idafa: chain idafa, idafa with adjectives, and restrictions on mudaf.",
        qs: [{ q: "In idafa, the mudaf cannot have:", o: ["Damma", "al- or tanwin", "Kasra", "Fatha"], c: "al- or tanwin" }, { q: "The mudaf ilayhi is always:", o: ["Marfu'", "Mansub", "Majrur", "Majzum"], c: "Majrur" }, { q: "A chain idafa can have:", o: ["Only two nouns", "Two or more nouns", "Only three", "Only one"], c: "Two or more nouns" }, { q: "In باب بيت المعلم, links are:", o: ["One", "Two", "Three", "Four"], c: "Two" }, { q: "Translate: باب بيت المعلم", o: ["The teacher's house", "Door of the teacher's house", "Teacher opened the door", "A house and door"], c: "Door of the teacher's house" }, { q: "Translate: كتاب الطالب", o: ["The student", "The student's book", "A book for students", "Books"], c: "The student's book" }, { q: "Translate: قلم المعلم", o: ["The teacher", "The teacher's pen", "A pen", "Pens"], c: "The teacher's pen" }, { q: "What does مضاف mean?", o: ["Added to", "Possessor/Annexed", "Possessed", "Independent"], c: "Possessor/Annexed" }, { q: "What does مضاف إليه mean?", o: ["Possessor", "Possessed/Added to it", "Independent", "Adjective"], c: "Possessed/Added to it" }, { q: "What does إضافة mean?", o: ["Addition", "Possessive construction", "Subtraction", "Coordination"], c: "Possessive construction" }]
    },
    {
        id: 70, t: "Substitution (Badal)", g: "Al-Badal", d: "Badal (substitution/apposition) follows a noun and takes the same i'rab.",
        qs: [{ q: "Badal takes the same i'rab as:", o: ["The verb", "The preceding noun", "The following noun", "The preposition"], c: "The preceding noun" }, { q: "بدل كل من كل means:", o: ["Partial", "Total substitution", "Inclusive", "Erroneous"], c: "Total substitution" }, { q: "بدل بعض means:", o: ["Total", "Partial substitution", "Inclusive", "Erroneous"], c: "Partial substitution" }, { q: "بدل اشتمال means:", o: ["Total", "Partial", "Inclusive substitution", "Error"], c: "Inclusive substitution" }, { q: "Translate: جاء محمد أخوك", o: ["Muhammad and your brother", "Muhammad your brother came", "Your brother is Muhammad", "Muhammad left"], c: "Muhammad your brother came" }, { q: "Translate: أكلت الرغيف ثلثه", o: ["I ate the loaf", "I ate a third of the loaf", "Three loaves", "I ate bread"], c: "I ate a third of the loaf" }, { q: "Translate: أعجبني محمد علمه", o: ["Muhammad pleased me", "Muhammad's knowledge pleased me", "I liked Muhammad", "He is knowledgeable"], c: "Muhammad's knowledge pleased me" }, { q: "What does بدل mean?", o: ["Coordination", "Substitution/Apposition", "Emphasis", "Adjective"], c: "Substitution/Apposition" }, { q: "What does مبدل منه mean?", o: ["The substitute", "Word being substituted from", "Preposition", "Verb"], c: "Word being substituted from" }, { q: "What does اشتمال mean?", o: ["Total", "Partial", "Inclusion/Encompassing", "Error"], c: "Inclusion/Encompassing" }]
    },
    {
        id: 71, t: "Introduction to Rhetoric", g: "Balagha Introduction", d: "Balagha (البلاغة — Rhetoric) studies eloquent expression.",
        qs: [{ q: "How many branches does Balagha have?", o: ["Two", "Three", "Four", "Five"], c: "Three" }, { q: "Ma'ani studies:", o: ["Figures of speech", "Meanings and sentence construction", "Embellishment", "Vocabulary"], c: "Meanings and sentence construction" }, { q: "Bayan studies:", o: ["Sentence structure", "Figures of speech and clarity", "Embellishment", "Grammar"], c: "Figures of speech and clarity" }, { q: "Badi' studies:", o: ["Grammar", "Sentence structure", "Embellishment/Beautification", "Morphology"], c: "Embellishment/Beautification" }, { q: "Translate: بلاغة", o: ["Grammar", "Rhetoric/Eloquence", "Morphology", "Syntax"], c: "Rhetoric/Eloquence" }, { q: "Translate: تشبيه", o: ["Metaphor", "Simile", "Metonymy", "Irony"], c: "Simile" }, { q: "Translate: استعارة", o: ["Simile", "Metaphor", "Metonymy", "Personification"], c: "Metaphor" }, { q: "What does معاني mean?", o: ["Words", "Meanings", "Letters", "Sounds"], c: "Meanings" }, { q: "What does بيان mean?", o: ["Clarity/Elucidation", "Grammar", "Morphology", "Syntax"], c: "Clarity/Elucidation" }, { q: "What does بديع mean?", o: ["Grammar", "Embellishment/Novel beauty", "Morphology", "Syntax"], c: "Embellishment/Novel beauty" }]
    },
    {
        id: 72, t: "Qira\\'at Introduction", g: "Introduction to Quranic Readings", d: "Qira'at are the various authentic ways the Quran was recited.",
        qs: [{ q: "How many major Quranic readers are there?", o: ["Five", "Seven", "Ten", "Fourteen"], c: "Seven" }, { q: "How many canonical readings exist?", o: ["Seven", "Ten", "Fourteen", "Twenty"], c: "Ten" }, { q: "Qira'at are transmitted through:", o: ["Books only", "Chains of narration (isnad)", "Personal opinion", "Dreams"], c: "Chains of narration (isnad)" }, { q: "All readings must meet three conditions:", o: ["Old, Arabic, confirmed", "Authentic chain, Arabic grammar, Uthmani script", "Famous, old, clear", "Written, spoken, memorized"], c: "Authentic chain, Arabic grammar, Uthmani script" }, { q: "Translate: قراءات", o: ["Writings", "Quranic Readings", "Translations", "Interpretations"], c: "Quranic Readings" }, { q: "Translate: قارئ", o: ["Writer", "Reader/Reciter", "Teacher", "Student"], c: "Reader/Reciter" }, { q: "Translate: رواية", o: ["Story", "Narration/Transmission", "Book", "Chapter"], c: "Narration/Transmission" }, { q: "What does إسناد mean?", o: ["Memorization", "Chain of narration", "Text", "Commentary"], c: "Chain of narration" }, { q: "What does متواتر mean?", o: ["Weak", "Mass-transmitted", "Single-chain", "Unknown"], c: "Mass-transmitted" }, { q: "What does تجويد mean?", o: ["Translation", "Proper recitation/Beautification", "Writing", "Memorization"], c: "Proper recitation/Beautification" }]
    },
    {
        id: 73, t: "Quranic Vocabulary — 1", g: "Mufradat Al-Quran 1", d: "Key vocabulary commonly found in the Quran.",
        qs: [{ q: "What does رب mean?", o: ["Prophet", "Message", "Lord/Sustainer", "Human"], c: "Lord/Sustainer" }, { q: "What does إله mean?", o: ["Angel", "Deity/God", "Lord", "Master"], c: "Deity/God" }, { q: "What does آية mean?", o: ["Book", "Word", "Sign/Verse", "Chapter"], c: "Sign/Verse" }, { q: "What does سورة mean?", o: ["Book", "Verse", "Word", "Chapter"], c: "Chapter" }, { q: "What does نبي mean?", o: ["Angel", "Prophet", "Messenger", "Lord"], c: "Prophet" }, { q: "What does رسول mean?", o: ["Prophet", "Messenger", "Lord", "Angel"], c: "Messenger" }, { q: "What does مَلَك mean?", o: ["King", "Angel", "Prophet", "Human"], c: "Angel" }, { q: "What does وحي mean?", o: ["Inspiration/Revelation", "Dream", "Vision", "Message"], c: "Inspiration/Revelation" }, { q: "What does كتاب mean?", o: ["Verse", "Chapter", "Book", "Word"], c: "Book" }, { q: "What does هدى mean?", o: ["Light", "Guidance", "Mercy", "Peace"], c: "Guidance" }]
    },
    {
        id: 74, t: "Quranic Vocabulary — 2", g: "Mufradat Al-Quran 2", d: "Key vocabulary commonly found in the Quran.",
        qs: [{ q: "What does جنة mean?", o: ["Fire", "Garden/Paradise", "Sky", "Earth"], c: "Garden/Paradise" }, { q: "What does نار mean?", o: ["Light", "Fire/Hell", "Water", "Air"], c: "Fire/Hell" }, { q: "What does رحمة mean?", o: ["Anger", "Mercy", "Justice", "Power"], c: "Mercy" }, { q: "What does عذاب mean?", o: ["Reward", "Punishment", "Forgiveness", "Peace"], c: "Punishment" }, { q: "What does يوم القيامة mean?", o: ["Day of Judgement", "Day of Assembly", "The Last Day", "The Promised Day"], c: "Day of Judgement" }, { q: "What does آخرة mean?", o: ["The Beginning", "The End/Hereafter", "The World", "Life"], c: "The End/Hereafter" }, { q: "What does دنيا mean?", o: ["This World/Life", "The Hereafter", "Heaven", "Hell"], c: "This World/Life" }, { q: "What does مؤمن mean?", o: ["Disbeliever", "Believer", "Hypocrite", "Polytheist"], c: "Believer" }, { q: "What does كافر mean?", o: ["Believer", "Disbeliever", "Hypocrite", "Polytheist"], c: "Disbeliever" }, { q: "What does شرك mean?", o: ["Faith", "Polytheism", "Atheism", "Hypocrisy"], c: "Polytheism" }]
    },
    {
        id: 75, t: "Quranic Vocabulary — 3", g: "Mufradat Al-Quran 3", d: "Key verbs commonly found in the Quran.",
        qs: [{ q: "What does خلق mean?", o: ["Made", "Created", "Said", "Did"], c: "Created" }, { q: "What does جعل mean?", o: ["Created", "Made/Set", "Said", "Did"], c: "Made/Set" }, { q: "What does آمن mean?", o: ["Believed", "Disbelieved", "Fought", "Ran"], c: "Believed" }, { q: "What does كفر mean?", o: ["Believed", "Disbelieved/Ingrate", "Fought", "Ran"], c: "Disbelieved/Ingrate" }, { q: "What does قال mean?", o: ["Did", "Made", "Said", "Created"], c: "Said" }, { q: "What does علم mean?", o: ["Knew", "Saw", "Heard", "Spoke"], c: "Knew" }, { q: "What does سمِع mean?", o: ["Knew", "Saw", "Heard", "Spoke"], c: "Heard" }, { q: "What does رأى mean?", o: ["Knew", "Saw", "Heard", "Spoke"], c: "Saw" }, { q: "What does جاء mean?", o: ["Went", "Left", "Arrived/Came", "Ran"], c: "Arrived/Came" }, { q: "What does ذهب mean?", o: ["Came", "Went", "Ran", "Slept"], c: "Went" }]
    },
    {
        id: 76, t: "Idiomatic Expressions", g: "Ta\\'birat Istilahiyya", d: "Arabic idioms map creatively to literal meanings.",
        qs: [{ q: "What does قرة عين (qurratu ayn) mean?", o: ["Eye pain", "Source of joy/comfort", "Tearful eye", "Blindness"], c: "Source of joy/comfort" }, { q: "What does ضرب به عرض الحائط mean?", o: ["He painted the wall", "He hit the wall", "He ignored it completely", "He built a wall"], c: "He ignored it completely" }, { q: "What does على الرأس والعين mean?", o: ["On the head and eye", "Gladly/With pleasure", "A headache", "Eye drops"], c: "Gladly/With pleasure" }, { q: "What does بين نارين mean?", o: ["Between two fires/A dilemma", "In the fire", "Safe from fire", "Cooking"], c: "Between two fires/A dilemma" }, { q: "Translate: عن ظهر قلب", o: ["By heart/Memorized", "From the back", "Heartless", "Back pain"], c: "By heart/Memorized" }, { q: "Translate: حبر على ورق", o: ["Ink on paper/Worthless", "Valuable document", "Writing", "Book"], c: "Ink on paper/Worthless" }, { q: "Translate: بيت القصيد", o: ["The poem's house", "The main point/Crux", "A long poem", "A small house"], c: "The main point/Crux" }, { q: "What does خط أحمر mean?", o: ["Red line/Boundary", "Red pen", "Blood", "Danger"], c: "Red line/Boundary" }, { q: "What does طويل الأمد mean?", o: ["Tall person", "Long-term", "Short-term", "Long distance"], c: "Long-term" }, { q: "What does غسيل أموال mean?", o: ["Washing machines", "Money laundering", "Clean money", "Rich person"], c: "Money laundering" }]
    },
    {
        id: 77, t: "Proverbs and Sayings", g: "Amthal wa Hikam", d: "Arabic proverbs (أمثال) hold cultural wisdom.",
        qs: [{ q: "What does الوقت كالسيف mean?", o: ["Swords take time", "Time is a sword", "Time is like a sword", "Time kills"], c: "Time is like a sword" }, { q: "What does من جد وجد mean?", o: ["Whoever seeks finds", "Whoever is serious achieves", "Whoever plays wins", "Whoever sleeps loses"], c: "Whoever is serious achieves" }, { q: "What does العلم في الصغر كالنقش في الحجر mean?", o: ["Learning is hard", "Learning young is like engraving in stone", "Stones are hard", "Children like stones"], c: "Learning young is like engraving in stone" }, { q: "What does رب أخ لك لم تلده أمك mean?", o: ["Brother from another mother", "Many brothers", "Your mother's brother", "No brothers"], c: "Brother from another mother" }, { q: "What does الصبر مفتاح الفرج mean?", o: ["Keys open doors", "Patience is the key to relief", "Relief is far", "Patience is hard"], c: "Patience is the key to relief" }, { q: "Translate: عصفور في اليد خير من عشرة على الشجرة", o: ["A bird in hand is worth two in the bush", "Ten birds", "Birds fly", "Trees have birds"], c: "A bird in hand is worth two in the bush" }, { q: "Translate: الجار قبل الدار", o: ["Houses are big", "The neighbor before the house", "Buy a house", "Neighbors are noisy"], c: "The neighbor before the house" }, { q: "What does الطيور على أشكالها تقع mean?", o: ["Birds of a feather flock together", "Birds fly high", "Birds fall", "Birds sing"], c: "Birds of a feather flock together" }, { q: "What does في التأني السلامة mean?", o: ["Safety is in caution/slowness", "Fast is dangerous", "Safety first", "Slow down"], c: "Safety is in caution/slowness" }, { q: "What does وفي العجلة الندامة mean?", o: ["Regret is fast", "In haste there is regret", "Haste makes waste", "Regret is bad"], c: "In haste there is regret" }]
    },
    {
        id: 78, t: "Poetry Introduction", g: "Muqaddima fi al-Shi\\'r", d: "Arabic poetry (الشعر العربي) is highly structured with specific meters (بحور) and rhymes (قوافي).",
        qs: [{ q: "An Arabic poem is generally composed of:", o: ["Paragraphs", "Verses/Lines (Abyat)", "Chapters", "Pages"], c: "Verses/Lines (Abyat)" }, { q: "A single line of classical poetry has:", o: ["One part", "Two hemistichs (Sadr and 'Ajuz)", "Three parts", "Four parts"], c: "Two hemistichs (Sadr and 'Ajuz)" }, { q: "What does بيت mean in poetry?", o: ["House", "A line of poetry", "A rhyme", "A meter"], c: "A line of poetry" }, { q: "What does قافية mean?", o: ["Rhyme", "Rhythm", "Meaning", "Word"], c: "Rhyme" }, { q: "What does بحر mean in poetry?", o: ["Sea", "Poetic Meter", "Rhyme", "Poem"], c: "Poetic Meter" }, { q: "The first half of the line is called:", o: ["'Ajuz", "Sadr", "Qafiya", "Bahr"], c: "Sadr" }, { q: "The second half of the line is called:", o: ["Sadr", "'Ajuz", "Qafiya", "Bahr"], c: "'Ajuz" }, { q: "What does قصيدة mean?", o: ["Story", "Poem/Ode", "Song", "Letter"], c: "Poem/Ode" }, { q: "What does شاعر mean?", o: ["Poem", "Poet", "Singer", "Writer"], c: "Poet" }, { q: "What does ديوان mean?", o: ["Court", "Collection of poems", "School", "Market"], c: "Collection of poems" }]
    },
    {
        id: 79, t: "Famous Poets", g: "Ash\\'ar wa Shu\\'ara\\'", d: "Famous Arabic poets include Al-Mutanabbi, Imru' al-Qais, and Ahmad Shawqi.",
        qs: [{ q: "Who is the famous pre-Islamic poet known for the Mu'allaqat?", o: ["Al-Mutanabbi", "Ahmad Shawqi", "Imru' al-Qais", "Nizar Qabbani"], c: "Imru' al-Qais" }, { q: "Who is often considered the greatest Arab poet (Abbasid era)?", o: ["Imru' al-Qais", "Al-Mutanabbi", "Ahmad Shawqi", "Mahmoud Darwish"], c: "Al-Mutanabbi" }, { q: "Who is known as \"The Prince of Poets\" in the modern era?", o: ["Ahmad Shawqi", "Al-Mutanabbi", "Imru' al-Qais", "Abu Nuwas"], c: "Ahmad Shawqi" }, { q: "What are the Mu'allaqat?", o: ["Suspended Odes (famous pre-Islamic poems)", "Modern poems", "Short stories", "Novels"], c: "Suspended Odes (famous pre-Islamic poems)" }, { q: "Al-Mutanabbi is most famous for poems of:", o: ["Love", "Pride and wisdom", "Nature", "Animals"], c: "Pride and wisdom" }, { q: "What does معلقة mean?", o: ["Suspended/Hung", "Written", "Spoken", "Hidden"], c: "Suspended/Hung" }, { q: "What does أمير الشعراء mean?", o: ["King of Writers", "Prince of Poets", "Best Poet", "First Poet"], c: "Prince of Poets" }, { q: "What does عصر جاهلي mean?", o: ["Islamic Era", "Pre-Islamic Era", "Modern Era", "Golden Age"], c: "Pre-Islamic Era" }, { q: "What does حكمة mean?", o: ["Love", "Wisdom", "War", "Peace"], c: "Wisdom" }, { q: "What does فخر mean?", o: ["Love", "Wisdom", "Pride/Boasting", "Sadness"], c: "Pride/Boasting" }]
    },
    {
        id: 80, t: "Numbers Review 1-100", g: "Al-A\\'dad 1-100", d: "Review of Arabic numbers 1-100. Remember the rules of agreement/disagreement in gender and the case of the counted noun.",
        qs: [{ q: "Numbers 1-2:", o: ["Disagree in gender", "Agree in gender with the noun", "Have no gender", "Always plural"], c: "Agree in gender with the noun" }, { q: "Numbers 3-10:", o: ["Agree in gender", "Disagree in gender with the noun", "Never change", "Always take al-"], c: "Disagree in gender with the noun" }, { q: "The counted noun for 3-10 is:", o: ["Singular Mansub", "Plural Majrur", "Singular Marfu'", "Plural Mansub"], c: "Plural Majrur" }, { q: "The counted noun for 11-99 is:", o: ["Plural Majrur", "Singular Mansub", "Singular Majrur", "Singular Marfu'"], c: "Singular Mansub" }, { q: "Translate: مائة كتاب", o: ["One book", "100 books", "1000 books", "10 books"], c: "100 books" }, { q: "Translate: عشرون طالباً", o: ["10 students", "20 students", "30 students", "100 students"], c: "20 students" }, { q: "Translate: خمس سيارات", o: ["5 cars", "6 cars", "7 cars", "8 cars"], c: "5 cars" }, { q: "What is 50 in Arabic?", o: ["عشرون", "خمسون", "ستون", "سبعون"], c: "خمسون" }, { q: "What is 11 in Arabic?", o: ["أحد عشر", "اثنا عشر", "ثلاثة عشر", "أربعة عشر"], c: "أحد عشر" }, { q: "What is 100 in Arabic?", o: ["عشرة", "مائة", "ألف", "مليون"], c: "مائة" }]
    },
    {
        id: 81, t: "Complex Numbers & Fractions", g: "Al-Kusur wa Al-A\\'dad", d: "Fractions in Arabic follow the pattern فُعْلٌ (e.g., رُبْعٌ for 1/4). To say \"half\", use نِصْفٌ.",
        qs: [{ q: "What does نصف mean?", o: ["Quarter", "Half", "Third", "Fifth"], c: "Half" }, { q: "What does ثلث mean?", o: ["Half", "Third", "Quarter", "Sixth"], c: "Third" }, { q: "What does ربع mean?", o: ["Third", "Quarter", "Fifth", "Half"], c: "Quarter" }, { q: "What does خمس mean?", o: ["Quarter", "Fifth", "Sixth", "Tenth"], c: "Fifth" }, { q: "What does عشر mean?", o: ["Fifth", "Tenth", "Eighth", "Ninth"], c: "Tenth" }, { q: "Translate: قرأت نصف الكتاب", o: ["I read the whole book", "I read half the book", "I read a third of the book", "I read a quarter of the book"], c: "I read half the book" }, { q: "Translate: الساعة الثالثة والربع", o: ["3:30", "3:15 (Three and a quarter)", "3:45", "4:15"], c: "3:15 (Three and a quarter)" }, { q: "Translate: الساعة الخامسة والنصف", o: ["5:30 (Five and a half)", "5:15", "6:30", "4:30"], c: "5:30 (Five and a half)" }, { q: "What does كسر mean in math?", o: ["Number", "Fraction", "Decimal", "Addition"], c: "Fraction" }, { q: "The pattern for fractions (1/3 to 1/10) is:", o: ["فَاعِلٌ", "فُعْلٌ", "مَفْعُولٌ", "فَعِيلٌ"], c: "فُعْلٌ" }]
    },
    {
        id: 82, t: "Telling Time", g: "Al-Waqt wa Al-Sa\\'a", d: "Telling time in Arabic involves Ordinal numbers for the hour (except 1) and fractions for minutes (ربع = quarter, ثلث = third/20 mins, نصف = half).",
        qs: [{ q: "To tell the hour, we use which type of numbers?", o: ["Cardinal numbers", "Ordinal numbers", "Fractions", "Decimals"], c: "Ordinal numbers" }, { q: "What is 1:00?", o: ["الساعة الأولى", "الساعة الواحدة", "الساعة الاثنان", "الساعة"], c: "الساعة الواحدة" }, { q: "What is 2:00?", o: ["الساعة الواحدة", "الساعة الثانية", "الساعة الثالثة", "الساعة"], c: "الساعة الثانية" }, { q: "What does وربع mean in time?", o: ["And a half", "And a quarter (15 past)", "Minus a quarter", "And 10 mins"], c: "And a quarter (15 past)" }, { q: "What does ونصف mean in time?", o: ["And a quarter", "And a half (30 past)", "Minus a half", "And 20 mins"], c: "And a half (30 past)" }, { q: "What does وثلث mean in time?", o: ["And a quarter", "And 20 minutes (a third)", "And a half", "Minus 20 mins"], c: "And 20 minutes (a third)" }, { q: "What does إلا ربعاً mean?", o: ["And a quarter", "Minus a quarter (15 to)", "And a half", "Minus a half"], c: "Minus a quarter (15 to)" }, { q: "Translate: الساعة الرابعة والنصف", o: ["4:15", "4:30", "5:30", "3:30"], c: "4:30" }, { q: "Translate: الساعة الخامسة إلا ثلثاً", o: ["5:20", "4:40 (20 to 5)", "5:40", "4:20"], c: "4:40 (20 to 5)" }, { q: "What does كم الساعة؟ mean?", o: ["Where is the watch?", "What time is it?", "How much is the clock?", "Is it time?"], c: "What time is it?" }]
    },
    {
        id: 83, t: "Days, Months, and Seasons", g: "Al-Ayyam wa Al-FUsul", d: "Vocabulary for Days of the week (الأيام), Months (الشهور), and Seasons (الفصول).",
        qs: [{ q: "What is Sunday?", o: ["الإثنين", "الأحد", "الثلاثاء", "الجمعة"], c: "الأحد" }, { q: "What is Monday?", o: ["الأحد", "الإثنين", "الأربعاء", "الخميس"], c: "الإثنين" }, { q: "What is Friday?", o: ["الخميس", "الجمعة", "السبت", "الأحد"], c: "الجمعة" }, { q: "What does شهر mean?", o: ["Day", "Week", "Month", "Year"], c: "Month" }, { q: "What does سنة / عام mean?", o: ["Day", "Week", "Month", "Year"], c: "Year" }, { q: "What is Spring?", o: ["الصيف", "الربيع", "الخريف", "الشتاء"], c: "الربيع" }, { q: "What is Summer?", o: ["الربيع", "الصيف", "الخريف", "الشتاء"], c: "الصيف" }, { q: "What is Autumn/Fall?", o: ["الشتاء", "الخريف", "الصيف", "الربيع"], c: "الخريف" }, { q: "What is Winter?", o: ["الربيع", "الصيف", "الخريف", "الشتاء"], c: "الشتاء" }, { q: "What does فصل mean?", o: ["Day", "Season/Chapter", "Month", "Week"], c: "Season/Chapter" }]
    },
    {
        id: 84, t: "Advanced Prepositions and Conjunctions", g: "Huruf Al-Jarr wa Al-\\'Atf", d: "Advanced usage of prepositions (حروف الجر) and conjunctions (حروف العطف). Includes words like حتى (until/even), بَلْ (rather), لَكِنْ (but).",
        qs: [{ q: "What does حتى mean?", o: ["Because", "Until/Even", "But", "Or"], c: "Until/Even" }, { q: "What does بَلْ mean?", o: ["Until", "Rather/Instead", "But", "And"], c: "Rather/Instead" }, { q: "What does لَكِنْ mean?", o: ["But/However", "And", "Or", "Because"], c: "But/However" }, { q: "What does أَوْ mean?", o: ["And", "But", "Or (used in statements)", "Or (in questions)"], c: "Or (used in statements)" }, { q: "What does أَمْ mean?", o: ["And", "But", "Or (used in questions with hal/hamza)", "Then"], c: "Or (used in questions with hal/hamza)" }, { q: "Translate: ما جاء محمد بل علي", o: ["Muhammad came, then Ali", "Muhammad did not come, rather Ali did", "Muhammad and Ali came", "Ali did not come"], c: "Muhammad did not come, rather Ali did" }, { q: "Translate: قرأت الكتاب حتى النهاية", o: ["I read the book quickly", "I read the book until the end", "I did not read the book", "I read some of the book"], c: "I read the book until the end" }, { q: "What does حرف عطف mean?", o: ["Preposition", "Conjunction", "Particle of negation", "Verb"], c: "Conjunction" }, { q: "What does ثمّ mean?", o: ["And", "Then (with a delay)", "Or", "But"], c: "Then (with a delay)" }, { q: "What does فـ mean in conjunctions?", o: ["And", "Then (immediately)", "Or", "But"], c: "Then (immediately)" }]
    },
    {
        id: 85, t: "Review: Sound Verbs", g: "Muraja\\'at Al-Fi\\'l Al-Sahih", d: "Comprehensive review of Sound Verbs (Salim, Mahmuz, Muda\\'\\'af).",
        qs: [{ q: "A Salim verb is a sound verb with:", o: ["Hamza", "Doubled letters", "Weak letters", "No hamza or doubled letters"], c: "No hamza or doubled letters" }, { q: "A Mahmuz verb contains:", o: ["Weak letters", "Hamza", "Doubled letters", "No weak letters"], c: "Hamza" }, { q: "A Muda\\'\\'af verb contains:", o: ["Hamza", "Doubled (geminated) root letter", "Weak root", "No hamza"], c: "Doubled (geminated) root letter" }, { q: "كتب is an example of:", o: ["Salim", "Mahmuz", "Muda\\'\\'af", "Weak"], c: "Salim" }, { q: "سأل is an example of:", o: ["Salim", "Mahmuz", "Muda\\'\\'af", "Weak"], c: "Mahmuz" }, { q: "ردّ is an example of:", o: ["Salim", "Mahmuz", "Muda\\'\\'af", "Weak"], c: "Muda\\'\\'af" }, { q: "Translate: كتب الدرس", o: ["He asked about the lesson", "He wrote the lesson", "He replied to the lesson", "He read the lesson"], c: "He wrote the lesson" }, { q: "Translate: سأل المعلم", o: ["He hit the teacher", "He asked the teacher", "He saw the teacher", "He wrote to the teacher"], c: "He asked the teacher" }, { q: "Translate: ردّ الجواب", o: ["He ignored the answer", "He returned/replied the answer", "He wrote the answer", "He asked the answer"], c: "He returned/replied the answer" }, { q: "What does صحيح mean for verbs?", o: ["Weak", "Broken", "Sound/Healthy (no weak letters)", "Past"], c: "Sound/Healthy (no weak letters)" }]
    },
    {
        id: 86, t: "Review: Weak Verbs", g: "Muraja\\'at Al-Fi\\'l Al-Mu\\'tall", d: "Comprehensive review of Weak Verbs (Mithal, Ajwaf, Naqis, Lafif).",
        qs: [{ q: "A Mithal verb has a weak letter in the:", o: ["First position", "Second position", "Third position", "None"], c: "First position" }, { q: "An Ajwaf (hollow) verb has a weak letter in the:", o: ["First position", "Second position", "Third position", "None"], c: "Second position" }, { q: "A Naqis verb has a weak letter in the:", o: ["First position", "Second position", "Third position", "None"], c: "Third position" }, { q: "A Lafif verb has:", o: ["One weak letter", "Two weak letters", "Three weak letters", "No weak letters"], c: "Two weak letters" }, { q: "وعد is an example of:", o: ["Mithal", "Ajwaf", "Naqis", "Lafif"], c: "Mithal" }, { q: "قال is an example of:", o: ["Mithal", "Ajwaf", "Naqis", "Lafif"], c: "Ajwaf" }, { q: "دعا is an example of:", o: ["Mithal", "Ajwaf", "Naqis", "Lafif"], c: "Naqis" }, { q: "Translate: وعدني خيراً", o: ["He asked me", "He promised me good", "He said to me", "He called me"], c: "He promised me good" }, { q: "Translate: قال الحق", o: ["He heard the truth", "He spoke the truth", "He wrote the truth", "He hid the truth"], c: "He spoke the truth" }, { q: "Translate: دعا ربه", o: ["He saw his Lord", "He called upon his Lord", "He forgot his Lord", "He praised his Lord"], c: "He called upon his Lord" }]
    },
    {
        id: 87, t: "Comprehensive Grammar Review 1", g: "Muraja\\'a Shāmila 1", d: "Comprehensive review of Nouns, Cases, Idafa, and Na\\'t.",
        qs: [{ q: "The default case of a noun is:", o: ["Mansub", "Majrur", "Marfu'", "Majzum"], c: "Marfu'" }, { q: "A noun after a preposition is:", o: ["Mansub", "Majrur", "Marfu'", "Majzum"], c: "Majrur" }, { q: "In an Idafa, the Mudaf Ilayhi is:", o: ["Mansub", "Majrur", "Marfu'", "Majzum"], c: "Majrur" }, { q: "The Na't (adjective) agrees with the Man'ut in:", o: ["Gender only", "Number only", "Case, gender, number, definiteness", "Case only"], c: "Case, gender, number, definiteness" }, { q: "Translate: الطالب الجديد", o: ["A new student", "The new student", "New students", "The student is new"], c: "The new student" }, { q: "Translate: في مدرسة كبيرة", o: ["In the big school", "In a big school", "Big schools", "A big school"], c: "In a big school" }, { q: "Translate: باب الغرفة", o: ["A room's door", "The door of the room", " Doors of rooms", "The open room"], c: "The door of the room" }, { q: "What is the case of السيارة في: ركبتُ السيارةَ؟", o: ["Marfu'", "Mansub", "Majrur", "Majzum"], c: "Mansub" }, { q: "What is the case of الطالب في: الطالبُ ذكيٌ؟", o: ["Marfu'", "Mansub", "Majrur", "Majzum"], c: "Marfu'" }, { q: "What is the case of الكتاب في: قرأت في الكتابِ؟", o: ["Marfu'", "Mansub", "Majrur", "Majzum"], c: "Majrur" }]
    },
    {
        id: 88, t: "Comprehensive Grammar Review 2", g: "Muraja\\'a Shāmila 2", d: "Comprehensive review of Inna, Kana, Verbal Sentences, and Numbers.",
        qs: [{ q: "Inna (إِنَّ) makes the subject (Mubtada'):", o: ["Marfu'", "Mansub", "Majrur", "Majzum"], c: "Mansub" }, { q: "Kana (كَانَ) makes the predicate (Khabar):", o: ["Marfu'", "Mansub", "Majrur", "Majzum"], c: "Mansub" }, { q: "A verbal sentence must start with:", o: ["A noun", "A verb", "A preposition", "A particle"], c: "A verb" }, { q: "In a verbal sentence, the doer (Fa'il) is:", o: ["Mansub", "Majrur", "Marfu'", "Majzum"], c: "Marfu'" }, { q: "Numbers 3-10: the counted noun is:", o: ["Singular Mansub", "Plural Majrur", "Singular Majrur", "Plural Marfu'"], c: "Plural Majrur" }, { q: "Translate: إن الله غفور", o: ["Allah was forgiving", "Indeed Allah is forgiving", "Is Allah forgiving?", "Allah is forgiving"], c: "Indeed Allah is forgiving" }, { q: "Translate: كان الجو بارداً", o: ["The weather is cold", "The weather was cold", "Indeed the weather is cold", "Cold weather"], c: "The weather was cold" }, { q: "Translate: يكتب الطالب الدرس", o: ["The student wrote the lesson", "The student is writing the lesson", "A lesson was written", "Write the lesson"], c: "The student is writing the lesson" }, { q: "Translate: خمسة كتب", o: ["Five books", "Fifteen books", "Fifty books", "Five pens"], c: "Five books" }, { q: "Translate: عشرون طالباً", o: ["Ten students", "Twenty students", "Two students", "Thirty students"], c: "Twenty students" }]
    }
];

lessons.forEach(l => {
    const content = mk(l.id, l.t, l.g, l.d, l.qs);
    fs.writeFileSync(path.join(__dirname, 'src', 'app', 'data', 'lessons', 'en', 'lesson_' + l.id + '.ts'), content);
});
console.log('Successfully created all 66-88 lessons.');
